name: CI-CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Run GO Tests
        working-directory: ./backend
        run: go test ./...

  build-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '14'
          cache: npm
          cache-dependency-path: frontend/package-lock.json
          
      - name: Check Node version 
        run: node --version

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs:
      - build-backend   # 🪓 Must match the exact job ID from above
      - build-frontend  # 🪓 Must match the exact job ID from above
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t backend:latest ./backend

      - name: Build frontend Docker image
        run: docker build -t frontend:latest ./frontend
